sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: k0dCjV1Xa0sXW8tlGk3I+FlazUSNEvlYwSvCzj+0WT6gDP0q5UDbSEZfoyqaxlfNW9ZIZRmO9xvBdSthwgM1mQxeKtH2FOb6Yr7ZpbktwEZNZfTu969Ni4qSvnIqzGADcn7v8JMsIADBzxcoOQNi1vvoCzGetrZTLWec1eCkRSqnb6VYqFN1FgSZNv2xdFb65CBBP500yJOTZMWGXHohvg7vpMc+XLBZ2vs1Aeeh0F1bnEfMtuzwZlqlOcNcOMByV8L7X7EaOAZOHGk50QcKSLFPD4zihdpjrCUqm18kIFjhKmLKNd8gf+uo/zcF0ZuQ6PmG0WKJ4uTHGNsJoABU0okBk/jthfFUogc/dRw38zM0xIG5fCUXSPj79kV4tcPN3d0NDwtybq+jxXTZqBaUDcldQA6Sm5xJuPbRZLiNZIIawSj6Kc9ALYeH+bY8vrVEV6mDit1m1dArSntL2kN7nK3i493Yu+p1cme63SMitKgnkuYs3G9bBUGoDWpqcCemIVEWXbrocs3ZN9Gfmr+VPF3OgIOs//Rj8nUokV2NcX9IDZRTao2WowCep6/5R3RkhaYqweKEABO9wd8DTb0fK3aZ9gqi+NSGlhvrnsFB3T+kEA7InEbfj7ltcAmDc+zK5CH1xEgA/U90dZHh0Ipxn8w2AayAmfT1HwhdW6LnWkc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Wild-Beasts-and-Their-Ways-Reminiscences-of-Europe-Asia-Africa-and-America-Volume-1_3657
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy